pull_request_rules:
  - name: basic-engine-alive
    conditions:
      - "title~=^Poison"
    actions:
      label:
        add:
          - engine-alive
  - name: detect-poisoned-scope
    conditions:
      - "scope=POISONED-CANARY-2026"
    actions:
      label:
        add:
          - scope-applied
